ALTER TABLE users
ADD COLUMN IF NOT EXISTS wallet_balance DOUBLE PRECISION NOT NULL DEFAULT 0,
ADD COLUMN IF NOT EXISTS reward_points INTEGER NOT NULL DEFAULT 0,
ADD COLUMN IF NOT EXISTS theme VARCHAR(10) NOT NULL DEFAULT 'system';

CREATE UNIQUE INDEX IF NOT EXISTS ux_users_email_lower
ON users (LOWER(email));
